### ISSUE TITLE
Hex Version

### ISSUE THREAD

**Issue by tielur** [dashbitco/broadway_cloud_pub_sub#81]
I'm getting this error:

`(MatchError) no match of right hand side value: {:error, %RuntimeError{message: "unexpected status 404 from Google\n\nNot Found\n\n"}} (broadway_cloud_pub_sub 0.7.1) lib/broadway_cloud_pub_sub/google_api_client.ex:43: BroadwayCloudPubSub.GoogleApiClient.conn!/2 (broadway_cloud_pub_sub 0.7.1) lib/broadway_cloud_pub_sub/google_api_client.ex:110: BroadwayCloudPubSub.GoogleApiClient.receive_messages/3 (broadway_cloud_pub_sub 0.7.1) lib/broadway_cloud_pub_sub/producer.ex:240: BroadwayCloudPubSub.Producer.handle_receive_messages/1 (broadway 1.0.3) lib/broadway/topology/producer_stage.ex:107: Broadway.Topology.ProducerStage.handle_demand/2 (gen_stage 1.1.2) lib/gen_stage.ex:2134: GenStage.noreply_callback/3 (stdlib 3.17.2) gen_server.erl:695: :gen_server.try_dispatch/4 (stdlib 3.17.2) gen_server.erl:771: :gen_server.handle_msg/6 (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3 Last message: {:"$gen_producer", {#PID<0.2367.0>, #Reference<0.3450931785.3144941569.156229>}, {:ask, 10}}`

It looks like there is some missing code that never got released to hex. Specifically #68 seems to be missing out of the latest hex version v0.7.1

Is there a way to get the latest released on hex? 🙏

**Comment by tielur** [comment]
Though maybe this isn't related to the PR linked above?

**Comment by tielur** [comment]
I think this may be related to GCP IAM permissions and the 404 is technically not finding the subscription. Going to close this for now
